name: Node.js CI demo deploiement

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: ./simpleApp

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Installer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Installer les dépendances
      working-directory: ./simpleApp
      run: npm install

    - name: Lancer les tests
      working-directory: ./simpleApp
      run: npm test